# docker-compose.yml
version: '3'
services:
  apache:
    image: httpd:2.4
    ports:
      - "8080:80"
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf